# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

install! 'cocoapods', :integrate_targets => false

target 'RNOpenCV' do
    pod 'OpenCV'
    pod 'React', :path => ‘../../../react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    # Add any other subspecs you want to use in your project
    ]
end

