#platform :ios, "8.0"
#use_frameworks!

target 'RNOpenCV-test' do
	
	pod 'React', :path => '../../../react-native', :subspecs => [
	  'RCTText',
	  'RCTImage',
	  'RCTNetwork',
	  'RCTWebSocket'
	]
end
